# Generated by Django 3.0.8 on 2022-11-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0002_bookauthor_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
